pub mod accurip;
pub mod audio;
pub mod audio_cd;
pub mod disc;
pub mod drive;
pub mod error;
pub mod extract;
pub mod flac;
pub mod filesystem;
pub mod formats;
pub mod image;
pub mod job;
pub mod logging;
pub mod media;
pub mod metadata;
pub mod multisession;
pub mod parallel;
pub mod progress;
pub mod rip;
pub mod settings;
pub mod types;

pub use accurip::{AccurateRipVerifier, AccurateRipResult, AccurateRipEntry, AccurateRipChecksum, calculate_crc32, calculate_file_crc32};
pub use drive::{DriveInfo, DriveScanner};
pub use disc::{DiscInfo, DiscType};
pub use error::DiskRipperError;
pub use extract::Extractor;
pub use flac::{FlacEncoder, FlacCompression, encode_to_flac};
pub use formats::{CdTextReader, DvdParser, ImageFormat, ImageFormatReader};
pub use image::Imager;
pub use job::{Job, JobId, JobManager, JobStatus};
pub use logging::{init_file_logging, get_log_dir, get_config_dir, get_cache_dir};
pub use media::MediaType;
pub use metadata::{CdTextInfo, CdTextParser, MusicBrainzLookup, FreedbLookup, MetadataProvider, DiscMetadata};
pub use parallel::{HardwareManager, GpuAccelerator, ParallelExtractor, ParallelProgress, ExtractResult, SystemInfo, GpuDevice, MemoryAwareReader};
pub use progress::ProgressTracker;
pub use rip::RipEngine;
pub use settings::{Settings, SettingsManager};
pub use types::*;
